# frozen_string_literal: true

require 'faraday'
require 'pry-byebug'

# SitemapGenerator handles generating sanitized sitemaps for our websites
# based on the external sitemaps generated by our vendors.
module SitemapGenerator
  class << self
    def child_sitemaps
      #   parent_body = get_parent_xml('https://cucumber.ghost.io/sitemap.xml')
      [
        'https://cucumber.ghost.io/sitemap-pages.xml',
        'https://cucumber.ghost.io/sitemap-posts.xml',
        'https://cucumber.ghost.io/sitemap-authors.xml',
        'https://cucumber.ghost.io/sitemap-tags.xml'
      ]
    end

    private

    def get_parent_xml(url)
      res = Faraday.get url

      res.body
    end
  end
end
