# frozen_string_literal: true

require 'faraday'
require 'pry-byebug'

# SitemapGenerator handles generating sanitized sitemaps for our websites
# based on the external sitemaps generated by our vendors.
module SitemapGenerator
  class << self
    def needs_update?(file_name)
      internal_last_modified = last_modified_date("https://cucumber.io/#{file_name}")
      external_last_modified = last_modified_date("https://cucumber.ghost.io/#{file_name}")

      Date.parse(internal_last_modified) < Date.parse(external_last_modified)
    end

    private

    def last_modified_date(url)
      res = Faraday.head url

      res.headers.dig('last-modified')
    end
  end
end
