# frozen_string_literal: true

# SitemapGenerator handles generating sanitized sitemaps for our websites
# based on the external sitemaps generated by our vendors.
module SitemapGenerator
  class << self
    def sanitize(input)
        dup = input.dup
        dup.gsub!('.ghost', '')
    end
  end
end
