# frozen_string_literal: true

require 'faraday'
require 'pry-byebug'

# SitemapGenerator handles generating sanitized sitemaps for our websites
# based on the external sitemaps generated by our vendors.
module SitemapGenerator
  # UpdateChecker informs the caller via needs_update? whether the passed in
  # site map name needs to be updated due to our current map's last modified
  # header being older than the current from our provider
  class UpdateChecker
    def needs_update?(file_name)
      internal_last_modified = get_last_modified("https://cucumber.io/#{file_name}")
      external_last_modified = get_last_modified("https://cucumber.ghost.io/#{file_name}")

      Date.parse(internal_last_modified) < Date.parse(external_last_modified)
    end

    private

    def get_last_modified(url)
      res = Faraday.get url

      res.headers.dig('last-modified')
    end
  end
end
