version: 2.1
executors:
  ruby:
    docker:
    - image: circleci/ruby:2.3.8
  working_directory: ~/cucumber.io

commands:
  gems:
    description: "Install gems needed for testing"
    steps:
      - restore_cache:
        keys:
          - v1-gemfile-{{ checksum "Gemfile.lock" }}
      - run: gem install bundler
      - run: bundle install --path vendor/bundle
      - save_cache:
        key: v1-gemfile-{{ checksum "Gemfile.lock" }}
        when: on_success
        paths:
          - ~/cucumber.io/vendor/bundle
  
  rspec:
    description: "Run rspec tests"
    steps:
      - run: bundle exec rspec
  
  nginx:
    description: "Install and configure NGINX for testing"
    steps:
      - run: sudo apt-get install nginx
      - run: sed -i -e "s|\$PORT|9001|" -e "s|\$NAME|localhost|" ./nginx/server.conf
      - run: sed -i "1d" ./nginx/nginx.conf
      - run: sed -i "31d" ./nginx/nginx.conf
      - run: sudo cp nginx/*.conf /etc/nginx/
      - run: sudo nginx
  
  docker:
    description: "Setup, build, and login to Docker"
    steps:
      - setup_remote_docker
      - run: docker build -t web .
      - run: docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com

  heroku:
    description: "Install heroku CLI then push and release the Heroku app"
    steps:
      - run: curl https://cli-assets.heroku.com/install.sh | sh
      - run: heroku container:push web --app cucumber-io-proxy
      - run: heroku container:release web --app cucumber-io-proxy

jobs:
  build_and_deploy:
    executor: ruby
    steps:
      - checkout
      - docker
      - heroku

  test:
    executor: ruby
    steps:
      - checkout
      - nginx
      - gems
      - rspec

workflows:
  version: 2
  test:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              only: master
