aliases:
  - &install_now
    name: Install Now
    command: npm install now
  - &deploy
    name: Deploy using zeit.co's now
    command: NOW && NOW alias  

defaults: &defaults
  docker:
    - image: circleci/node
  environment:
    NOW: ./node_modules/.bin/now --team cucumber --token $NOW_TOKEN

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: *install_now
      - run: *deploy