version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install -g now
      - run: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
