aliases:
  - &deploy
    name: Deploy using Heroku
    command: |
      docker build -t web .
      heroku container:push web --app cucumber-io-proxy
      heroku container:release web --app cucumber-io-proxy

defaults: &defaults
  docker:
    - image: buildpack-deps:trusty

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: *deploy
