version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker build -t web .
          docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:push web --app cucumber-io-proxy
          heroku container:release web --app cucumber-io-proxy
    branches:
      only:
        - master
