version: 2
build_defaults: &build_defaults
  docker:
  - image: circleci/ruby:2.3.8

jobs:
  build_and_deploy:
    <<: *build_defaults
    steps:
      - checkout
      - run: |
          docker build -t web .
          docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:push web --app cucumber-io-proxy
          heroku container:release web --app cucumber-io-proxy

  test_image:
    <<: *build_defaults
    steps:
      - checkout
      - run: |
          docker build -t web --build-arg PORT=9001 --build-arg NAME=localhost .
          docker run -i --name web -p 9001:9001 -d --rm web
          bundle install
          bundle exec rspec

  stop_test_image:
    <<: *build_defaults
    steps:
      - checkout
      - run: docker stop web

workflows:
  version: 2
  test:
    jobs:
      - test_image
      - stop_test_image:
          requires:
            - test_image
      - build_and_deploy:
          filters:
            branches:
              only: master
