version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install now
      - run: cd project
      - run: ./node_modules/.bin/now --public --token $NOW_TOKEN && ./node_modules/.bin/now alias --token $NOW_TOKEN
