version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker build -t web .
          heroku container:push web --app cucumber-io-proxy
          heroku container:release web --app cucumber-io-proxy

