aliases:
  - &install_now
    name: Install Now
    command: npm install now
  - &deploy
    name: Deploy using zeit.co's now
    command: |
      export NOW="./node_modules/.bin/now --regions bru --no-verify --team cucumber --token $NOW_TOKEN"
      $NOW && $NOW alias

defaults: &defaults
  docker:
    - image: circleci/node

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: *install_now
      - run: *deploy