version: 2
build_defaults: &build_defaults
  docker:
  - image: circleci/ruby:2.3.8

jobs:
  build_and_deploy:
    <<: *build_defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t web .
          docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:push web --app cucumber-io-proxy
          heroku container:release web --app cucumber-io-proxy

  test_image:
    <<: *build_defaults
    steps:
      - checkout
      - run: |
          sudo apt-get install nginx
          sed -i -e "s|\$PORT|9001|" -e "s|\$NAME|localhost|" ./nginx/server.conf
          sudo cp nginx/*.conf /etc/nginx/
          sudo nginx
          gem install bundler
          bundle install
          bundle exec rspec

workflows:
  version: 2
  test:
    jobs:
      - test_image
      - build_and_deploy:
          filters:
            branches:
              only: master
